spring:
  application:
    name: AfterNote-Server

  datasource:
    url: jdbc:mysql://afternote-db.czu4saqqeacc.ap-northeast-2.rds.amazonaws.com:3306/afternote?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: xpZx2Sy5JYbve9J
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.example.afternote: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
